version: "3.9"
services:
  web:
    stop_signal: SIGINT
    restart: unless-stopped
    build: .
    environment:
      SECRET_KEY: ''
      CLIENT_ID: ''
      CLIENT_SECRET: ''
      CLIENT_REDIRECT_URI: ''
      ALLOWED_GUILD_ID: ""
      S3_ENDPOINT_URL: ""
      S3_ACCESS_KEY_ID: ""
      S3_SECRET_KEY: ""
      S3_BUCKET_NAME: ""
    volumes:
      - './:/app'
    ports:
        - "8080:80"